// ACTION TYPES
//users
export const USERS = 'USERS'
export const USER_BY_ID = 'USER_BY_ID'

export const LOGIN = 'LOGIN'

export const NEW_USER = 'NEW_USER'

export const UPDATE_USER = 'UPDATE_USER'

export const DELETE_USER = 'DELETE_USER'
//photos
export const NEW_PHOTO = 'NEW_PHOTO'

export const DELETE_PHOTO = 'DELETE_PHOTO'

// MUTATION TYPES
//users
export const USERS_REQUEST = 'USERS REQUEST'
export const USERS_RESPONSE = 'USERS RESPONSE'
export const USERS_ERRORS = 'USERS ERRORS'
export const SINGLE_USER_RESPONSE = 'SINGLE_USER_RESPONSE'

export const LOGIN_REQUEST = 'LOGIN REQUEST'
export const LOGIN_RESPONSE = 'LOGIN RESPONSE'
export const LOGIN_ERRORS = 'LOGIN ERRORS'

export const NEW_USER_REQUEST = 'NEW_USERS REQUEST'
export const NEW_USER_RESPONSE = 'NEW_USERS RESPONSE'
export const NEW_USER_ERRORS = 'NEW_USERS ERRORS'

export const UPDATE_USER_REQUEST = 'UPDATE_USERS REQUEST'
export const UPDATE_USER_RESPONSE = 'UPDATE_USERS RESPONSE'
export const UPDATE_USER_ERRORS = 'UPDATE_USERS ERRORS'

export const DELETE_USER_REQUEST = 'DELETE_USERS REQUEST'
export const DELETE_USER_RESPONSE = 'DELETE_USERS RESPONSE'
export const DELETE_USER_ERRORS = 'DELETE_USERS ERRORS'
//photo
export const NEW_PHOTO_REQUEST = 'NEW_PHOTO REQUEST'
export const NEW_PHOTO_RESPONSE = 'NEW_PHOTO RESPONSE'
export const NEW_PHOTO_ERRORS = 'NEW_PHOTO ERRORS'

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO REQUEST'
export const DELETE_PHOTO_RESPONSE = 'DELETE_PHOTO RESPONSE'
export const DELETE_PHOTO_ERRORS = 'DELETE_PHOTO ERRORS'

// GETTER TYPES
export const GET_USER_BY_ID = 'GET_USER_BY_ID'


